### ISSUE TITLE
Restrict Process execution to Permission

### ISSUE THREAD

**Issue by ctippler** [elements-at/ProcessManager#166]

**Comment by NiklasBr** [comment]
Got this message after updating and no configurations are available in the UI.

```
Timestamp: Fri Feb 17 2023 10:54:33 GMT+0100 (centraleuropeisk normaltid)
Status: 500 | Internal Server Error
URL: /admin/elementsprocessmanager/index/get-plugin-config
Message: Elements\Bundle\ProcessManagerBundle\Model\Configuration::setRestrictToPermissions(): Argument #1 ($restrictToPermissions) must be of type array|string, null given, called in /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php on line 205
Trace: 
in /var/www/pimcore/vendor/elements/process-manager-bundle/src/Model/Configuration.php:416
#0 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(205): Elements\Bundle\ProcessManagerBundle\Model\Configuration->setRestrictToPermissions(NULL)
#1 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(187): Pimcore\Model\AbstractModel->setValue('restrictToPermi...', NULL)
#2 /var/www/pimcore/vendor/elements/process-manager-bundle/src/Model/Dao/AbstractDao.php(73): Pimcore\Model\AbstractModel->setValues(Array)
#3 /var/www/pimcore/vendor/elements/process-manager-bundle/src/Model/Configuration/Dao.php(85): Elements\Bundle\ProcessManagerBundle\Model\Dao\AbstractDao->getById('4')
#4 /var/www/pimcore/vendor/elements/process-manager-bundle/src/Model/Configuration.php(134): Elements\Bundle\ProcessManagerBundle\Model\Configuration\Dao->getById('4')
#5 /var/www/pimcore/vendor/elements/process-manager-bundle/src/Model/Configuration/Listing/Dao.php(40): Elements\Bundle\ProcessManagerBundle\Model\Configuration::getById('4')
#6 [internal function]: Elements\Bundle\ProcessManagerBundle\Model\Configuration\Listing\Dao->load()
#7 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(245): call_user_func_array(Array, Array)
#8 /var/www/pimcore/vendor/elements/process-manager-bundle/src/Controller/IndexController.php(92): Pimcore\Model\AbstractModel->__call('load', Array)
#9 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(163): Elements\Bundle\ProcessManagerBundle\Controller\IndexController->getPluginConfigAction(Object(Symfony\Component\HttpFoundation\Request), Object(Elements\Bundle\ProcessManagerBundle\Service\CommandsValidator), Object(Pimcore\Translation\Translator))
#10 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/pimcore/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
```

**Comment by ctippler** [comment]
Hi, have you also executed 
./bin/console doctrine:migrations:migrate --prefix=Elements\\Bundle\\ProcessManagerBundle 

Does the bundle_process_manager_configuration table has a  column "restrictToPermissions"?

regards,
Christian

**Comment by ctippler** [comment]
Could you pleas try to update to 4.1.1 - the latest migration should fix the issue

**Comment by NiklasBr** [comment]
Works great now, thanks! 🙇
