### ISSUE TITLE
Error when accessing tasks list in backend

### ISSUE THREAD

**Issue by FredoVelcro** [elements-at/ProcessManager#43]
Hello,

I use Process Manager v 3.0.11 and Pimcore latest (dev-master)
When trying to access the tasks panel in backend, i have a modal with this error :

```
Timestamp: Fri Dec 13 2019 15:05:37 GMT+0100 (heure normale d’Europe centrale)
Status: 500 | Internal Server Error
URL: /admin/elementsprocessmanager/index/get-plugin-config
Message: Call to a member function getGroup() on null
Trace: 
in /var/www/html/vendor/elements/process-manager-bundle/src/Controller/IndexController.php:104
#0 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(146): Elements\Bundle\ProcessManagerBundle\Controller\IndexController->getPluginConfigAction(Object(Symfony\Component\HttpFoundation\Request))
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#3 /var/www/html/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
```

I tried to empty caches, reinstall the bundle, empty vendors, composer update etc always the same...
Any idea ?

Best regards.

**Comment by AlternateIf** [comment]
@FredoVelcro do you have anything in your plugin_process_manager_configuration table? you may try deleting entries there.

**Comment by AlternateIf** [comment]
also check if all migrations have been executed successfully by checking the migrations table

**Comment by FredoVelcro** [comment]
Ok, deleting the tables, reinstalling the bundle via backend extensions management and all is ok !
Now i have another problem :  
```
ERROR:Exception: The current system user is not allowed to execute this script. Allowed users: 'root' Executing user: 'www-data'. in /var/www/html/vendor/elements/process-manager-bundle/src/ExecutionTrait.php:206
Stack trace:
#0 /var/www/html/vendor/elements/process-manager-bundle/src/ExecutionTrait.php(114): AppBundle\Command\SampleCommand::checkExecutingUser(Array)
#1 /var/www/html/src/AppBundle/Command/SampleCommand.php(44): AppBundle\Command\SampleCommand::initProcessManager('2')
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): AppBundle\Command\SampleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(1029): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/ven
```

Note i use Docker, all my volume are mounted as "root" user.

**Comment by ckogler-elements** [comment]
Hi, 
it looks like the owner of your system.yml ist "root" which normaly should not be. Normaly the owner of your files should be "www-data". To fix it - change the owner of the system.yml (and all other files) to www-data. 

Option 2: 
Allow the www-data user in the plugin-process-manager.php config file. 
'general' => [
'additionalScriptExecutionUsers' => ['www-data']
]

should do the trick...

**Comment by AlternateIf** [comment]
@FredoVelcro have you been able to resolve the problem?

**Comment by FredoVelcro** [comment]
@ckogler-elements thanks it works now !
